data_type: 'all'  # 'a' for adults - 'k' for kids - 'all' for all
wave: '4th W'

figPath: './_figures'

VARS: [
  ['aggregate'],
  ['employed'], 
 ['education3'], 
 ['settlement_cur_num'],
 ['fin_now3a'],
  

# ['employed',education3],
# ['employed',fin_now3a]
  ]


VARS_plt: [
  ['employed'], 
  ['education3'], 
 ['settlement_cur_num'],
# ['fin_now3a'],
  

# ['employed',education3],
# ['employed',fin_now3a]
  ]




